Changed a lot, fixed some bugs, added old stuff, deleted openvpn , added new features

diff --git a/mcloud-1.3/usr/bin/mcloud-client b/mcloud-1.3/usr/bin/mcloud-client
--- a/mcloud-1.3/usr/bin/mcloud-client
+++ b/mcloud-1.3/usr/bin/mcloud-client
@@ -10,35 +10,19 @@ CONFIG_FILE_NAME="/etc/mcloud-config/mcloud-client.conf"
 
 CONFIG_CONTENTS=`cat $CONFIG_FILE_NAME`
 
-assignUser() {
-	echo "Todo: assigning user to github repo on central server"
-}
+if [ ! -f $CONFIG_FILE_NAME ]; then
+		echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
+		exit 1;
+fi
+eval $CONFIG_CONTENTS
 
 disconnectClientServer() {
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
-	eval $CONFIG_CONTENTS
-	echo "Disconnecting OpenVPN connection"
-	sudo killall openvpn
-
 	echo "Unmounting SSH mountpoint and tunnel"
 	sudo umount $LOCATION_SSHFS_MOUNTPOINT
 	sudo killall ssh
 }
 
 connectClientServer() {
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
-	eval $CONFIG_CONTENTS
-	echo "Opening client config file... "
-	exec 3< <(sudo /usr/sbin/openvpn --config $OPENVPN_CONFIG)
-	sed '/Initialization Sequence Completed$/q' <&3 ; cat <&3 &
-
-	echo "OPENVPN is connected"
 
 	echo "Calling mCloud server and creating tunnel"
 
@@ -48,14 +32,28 @@ connectClientServer() {
 
 }
 
+
+assignUser() {
+	echo "This script will run a remote script on the central peer server"
+	echo "Name of the repo"
+	read REPO_NAME
+
+	echo "Users, seperated by ; without spaces"
+	read USERS
+
+	ssh $USER@$CENTRAL_IP -o IdentityFile=$USER_RSA_FILE -p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "sudo /usr/bin/mcloud-user-addition $REPO_NAME $USERS"
+
+	echo "Reconnecting client and Server"
+	disconnectClientServer()
+	connectClientServer()
+
+
+
+}
+
+
 assignServer() {
 	echo "Assigning this client to a mCloud server"
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
-
-	eval $CONFIG_CONTENTS
 
 	if [ -z "$USER_RSA_FILE" ]; then
 		echo "Generating ssh key"
@@ -66,11 +64,11 @@ assignServer() {
 		echo "Getting contents of ssh key... ~/.ssh/id_rsa.pub"
 		echo "YOUR SSH KEY: "
 		cat ~/.ssh/id_rsa.pub
-		echo "You will receive an ovpn file from the mCloud server, place that one in your home directory. Rename it to: mcloudServer.ovpn"
-		sudo sh -c "echo \"OPENVPN_CONFIG=\"$HOME/mcloudServer.ovpn\"\" >> $CONFIG_FILE_NAME"
+		echo "What is the central server ip? (e.g. 95.234.12.65) (ask your central administrator): "
+		read CE_IP
 		sudo sh -c "echo \"USER=\"$USER\"\" >> $CONFIG_FILE_NAME"
 		sudo sh -c "echo \"USER_RSA_FILE=\"/home/$USER/.ssh/id_rsa\"\" >> $CONFIG_FILE_NAME"
-		sudo sh -c "echo \"CENTRAL_IP=\"10.8.0.1\"\" >> $CONFIG_FILE_NAME"
+		sudo sh -c "echo \"CENTRAL_IP=\"$CE_IP\"\" >> $CONFIG_FILE_NAME"
 	else
 		echo "You already generated an rsa file, please contact mCloud server for the IP-address and the OpenVPN config file"
 		echo "Contents of RSA key: "
@@ -81,23 +79,12 @@ assignServer() {
 
 }
 
-removeMCLOUD() {
-	echo "TODO: Removing MCLOUD package"
-}
-
 #########################
 # OPENING MCLOUD IMAGE  #
 #########################
 openEncryptedContainer() {
-
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
-
 	echo "Opening and mounting the already created mCloud instance.."
 
-	eval $CONFIG_CONTENTS
 	echo "Opening the image file: $IMAGE_FILE..."
 	sudo cryptsetup luksOpen $IMAGE_FILE $LOCAL_FILE_CONTAINER --key-file $KEY_FILE
 	echo "Mounting encrypted container..."
@@ -111,14 +98,7 @@ openEncryptedContainer() {
 #########################
 closeEncryptedContainer() {
 
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
-
 	echo "Closing the already mounted mCloud image."
-
-	eval $CONFIG_CONTENTS
 	echo "Umounting mountpoint: $LOCATION_MOUNTPOINT"
 	sudo umount $LOCATION_MOUNTPOINT
 	echo "Closing encrypted luksvolume"
diff --git a/mcloud-1.3/usr/bin/mcloud-server b/mcloud-1.3/usr/bin/mcloud-server
--- a/mcloud-1.3/usr/bin/mcloud-server
+++ b/mcloud-1.3/usr/bin/mcloud-server
@@ -8,19 +8,20 @@ CONFIG_FILE_NAME="/etc/mcloud-config/mcloud-server.conf"
 
 CONFIG_CONTENTS=`cat $CONFIG_FILE_NAME`
 
+if [ ! -f $CONFIG_FILE_NAME ]; then
+			echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
+			exit 1;
+fi
+
+eval $CONFIG_CONTENTS
+
 
 addUser() {
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-		    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-		    exit 1;
-	fi
-
-	eval $CONFIG_CONTENTS
 
 	echo "Add user to central peer using SSH-KEY PAIR"
 	echo "Please make sure you changed the ssh config file to only allow ssh-key pair login"
 
-	if [ -z "$HOME_DIRECTORY" ]; then 
+	if [ -z "$HOME_DIRECTORY" ]; then
 
 		echo "Specify the location to all the home directories of the user"
 		read HOME_LOCATION
@@ -76,22 +77,28 @@ addUser() {
 }
 
 removeUser() {
-	echo "TODO: Removing user from central peer"
+	echo "This will remove the user from the central server and also delete the home directory. After this the user can no longer access this central server."
+
+	echo "What user do you want to remove, specify username? (e.g. kip)"
+	read USER_DELETE
+
+	USER_HOME=`eval echo ~$USER_DELETE`
+	echo "Is the home directory?: $USER_HOME"
+	sudo userdel $USER_DELETE --remove
+
+	echo "SSH server restarting"
+	/etc/init.d/ssh restart
+
+	echo "====NOTE==== You have to remove the user from the exports file: /etc/exports. To make sure there is no more NFS access."
 }
 
 #########################
 # OPENING MCLOUD IMAGE  #
 #########################
 openEncryptedContainer() {
-	echo "Opening and mounting the already created mCloud instance.."
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
-	
+
 	echo "Opening and mounting the already created mCloud instance.."
 
-	eval $CONFIG_CONTENTS
 	echo "Opening the image file: $IMAGE_FILE..."
 	sudo cryptsetup luksOpen $IMAGE_FILE $LOCAL_FILE_CONTAINER --key-file $KEY_FILE
 	echo "Mounting encrypted container..."
@@ -105,16 +112,11 @@ openEncryptedContainer() {
 #########################
 closeEncryptedContainer() {
 	echo "Closing the already mounted mCloud image."
-	if [ ! -f $CONFIG_FILE_NAME ]; then
-	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
-	    exit 1;
-	fi
 
-	eval $CONFIG_CONTENTS
 	echo "Umounting mountpoint: $LOCATION_MOUNTPOINT"
 	sudo umount $LOCATION_MOUNTPOINT
 	echo "Closing encrypted luksvolume"
-	sudo cryptsetup luksClose $LOCAL_FILE_CONTAINER 
+	sudo cryptsetup luksClose $LOCAL_FILE_CONTAINER
 	echo "Mountpoint is closed"
 }
 
@@ -155,7 +157,7 @@ do
       -*)
           echo "Error: Unknown option: $1" >&2
           ## or call function display_help
-          exit 1 
+          exit 1
           ;;
       *)  # No more options
           break
@@ -163,7 +165,7 @@ do
     esac
 done
 
-###################### 
+######################
 # Check if parameter #
 # is set too execute #
 ######################
@@ -181,7 +183,7 @@ case "$1" in
     closeEncryptedContainer  ##added
     ;;
   *)
-	
+
 
      display_help
      exit 1
